apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: to-do-server
  template:
    metadata:
      labels:
        app: to-do-server
    spec:
      containers:
        - name: to-do-server
          image: quay.io/martinezj/to-do-server:latest
          ports:
            - containerPort: 3001
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "todo_db"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
